config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :employees
  ActiveAdmin.routes(self)

  resources :users, only: [:new,:create]
  get '/login', to: "sessions#login", as: "login"
  post '/login', to: "sessions#post_login"
  delete '/logout', to: "sessions#log_out", as: "logout"
  root "books#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Book
    can :create, Book
    can [:edit, :update, :destroy], Book, user: user
    if user.is_admin == true
      can :manage, Book
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  paginates_per 5
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password
  validates :name, :email, :gender, presence: true
  validates :password, presence: true
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  enum :gender, { male:"0", female:"1", other:"2" }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :skip_password
  validates_presence_of :name
  validates :password, presence: true, if: :skip_password
  validates :password, confirmation: true, if: :skip_password
  validates :password_confirmation, presence: true, if: :skip_password
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :is_authenticated, unless: :ordinary_controller
  before_action :not_loggedin, if: :ordinary_controller
  rescue_from CanCan::AccessDenied do |exception|
      flash[:alert] = "You are not authorized to #{exception.action} this #{exception.subject.class}"
      redirect_to root_path 
  end


  private
  def is_authenticated
      unless loggedin?
          flash[:alert] = "You should be logged-in to use this service"
          redirect_to login_path
      end
  end

  def not_loggedin
      if loggedin?
          flash[:alert] = "You are already logged-in as #{current_user.name}"
          redirect_to root_path
      end
  end

  def ordinary_controller
      if (params[:controller] == "sessions" && params[:action] != "log_out") || params[:controller] == "users"
          return true
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def new
    @book = Book.new 
  end

  def show
  end

  def create 
    @book.user_id = current_user.id
    if @book.save()
      redirect_to root_path
    end
  end

  def index(nxt=1)
    # if params[:nxt]
    #   nxt = params[:nxt]
    #   @nxt = nxt.to_i
    # else
    #   @nxt = nxt
    # end
    # @books = Book.page(@nxt)

    @books = Book.page(params[:page])
  end

  def edit 
  end

  def update
    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private
    def book_params
      params.require(:book).permit(:title)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new 
  end

  def create
    @employee = Employee.new(emp_params)
    @employee.user_id = current_user.id
    if @employee.save
      redirect_to root_path
    else
       render :new, status: :unprocessable_entity
    end
  end

  private
  def emp_params
    params.require(:employee).permit(:name, :email, :password, :password_confirmation, :gender, :birth_date)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
  end

  def post_login
      @user = User.find_by(name: params[:name])
      if @user && @user.authenticate(params[:password])
          log_in(@user)
          redirect_to root_path, notice: "You are successfully logged-in as #{@user.name}"
      else
          flash[:alert] = "Invalid Credentials!!"
          render :login, status: :unprocessable_entity
      end
  end

  def log_out # this is controller's action
      logout # this is calling helper method 
      redirect_to login_path, status: :see_other 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "User created successfully"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            current_user = User.find_by(id: session[:user_id])
        end
    end

    def loggedin?
        current_user.present?
    end

    def logout
        session[:user_id] = nil
    end
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Id:</strong>
    <%= book.id %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    ----------------
  <% end %>
</div>

<%# ------ Custom Pagination ------- %>

<%# <% if Book.page(@nxt+1).count > 0 %> 
  <%# <%= link_to "Next>>",books_path(nxt:@nxt+1) %> 
<%# <% end %> 
<%# <% if @nxt > 1 %> 
  <%# <%= link_to "<<Prev",books_path(nxt:@nxt-1) %> 
<%# <% end %> 

<%# ========================== %>

 <%# ------- Pagination with kaminari helpers -------- %>

<%= paginate @books, outer_window: 3 %>

<%# ===================== %>
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/employees/new.html.erb
<%= simple_form_for @employee do |f| %>
  <%= f.input :name, label: "Employee_Name" %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :gender, as: :select, collection: [['Male', 0], ['Female', 1], ['Other', 2]] %>
  <%= f.input :birth_date %>

  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GemPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:alert] %>
      <p class="alert alert-danger"> <%= flash[:alert] %> </p>
    <% end %>
    <% if notice %>
      <p class="alert alert-success"> <%= notice %> </p>
    <% end %>
    <%= yield %>
    <% if loggedin? %>
      <%= button_to "Log-out",logout_path, method: :delete %>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model:@user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.text_field :password %>
    </div>

    <div>
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation %>
    </div>

    <div>
        <%= f.submit 'Create' %>
    </div>

<% end %>